name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install tools
      - name: Install dependencies
        run: |
          pip install pylint pytest

      # 4. Lint
      - name: Run pylint
        run: pylint app.py || true

      # 5. Test
      - name: Run tests
        run: pytest

      # 6. Build artifact (NEW 🔥)
      - name: Create zip artifact
        run: zip -r app.zip .

      # 7. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: app.zip